apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      name: backend-pod
      namespace: chat-app
      labels:
        app: backend
    spec:
      containers:
      - name: backend 
        image: eyepatch5263/chat-backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: MONGO_URI
          value: mongodb://root:example@mongo:27017/eyetify?authSource=admin
        - name: JWT_SECRET_KEY
          valueFrom: 
            secretKeyRef:
              name: backend-secret
              key: JWT_SECRET_KEY 
        - name: PORT
          value: "8000"
        resources:
          requests:
            cpu: "1"
            memory: "512Mi"
          limits:
            cpu: "2"
            memory: "1024Mi"

---

apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: chat-app
spec:
  selector:
    app: backend
  ports:
  - port: 8000
    targetPort: 8000