apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: chat-app
type: Opaque
data:
  JWT_SECRET_KEY: c0JnVGNScXdhbTUveCtJQ2NQUi9jYk5pSFVSNm04ZmNkY21XMS9QeXVkST0=
#base 64 encoded string